// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import ()

type Actor struct {
	ID   int64
	Name string
}

type Character struct {
	ID      int64
	Name    string
	ActorID int64
}

type Quote struct {
	ID          int64
	CharacterID int64
	SceneID     int64
	Text        string
}

type Scene struct {
	ID   int64
	Name string
}

type SceneCharacter struct {
	SceneID     int64
	CharacterID int64
}
